name: 'Callabled Workflow'
description: 'A composite action to print environment and JFROG_PASSWORD'
inputs:
  environment:
    description: 'Environment to deploy to'
    required: true
    default: 'dev'
  JFROG_PASSWORD:
    description: 'JFROG password'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Print stuff
      shell: bash
      run: |
        echo "Hello ${{ inputs.environment }}"
        echo "JFROG_PASSWORD: ${{ inputs.JFROG_PASSWORD }}"
        echo "${{ inputs.JFROG_PASSWORD }}" | md5sum